pjt00/pjt00/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path("tclone/", include("tclone.urls")),
    path("tclone/", include("tweet.urls")),
    path("admin/", admin.site.urls),
]

pjt00/tclone/urls.py
from django.urls import include, path
from . import views

app_name= 'tclone'

urlpatterns = [
    path('', views.TopView.as_view(), name='top'),
    path('', include('django.contrib.auth.urls')),
    path('entry/', views.EntryUserView.as_view(), name='entry'),
    path('entry/ok', views.EntryOKView.as_view(), name='entryok'),
    path('profile/<int:pk>/follow', views.FollowView.as_view(), name='follow'),
    path('profile/<int:pk>/follow/delete', views.follow_del, name='follow_del')
    ]

pjt00/tweet/urls.py
from django.urls import path
from . import views

app_name= 'tweet'

urlpatterns = [
    path('home/', views.HomeView.as_view(), name='home'),
    path('profile/<int:pk>/', views.profile, name='profile'),
    path('tweet/', views.tweet, name='tweet'),
    path('tweet/<int:pk>/', views.tdetail, name='tdetail'),
    path('tweet/<int:pk>/edit/', views.tedit, name='tedit'),
    path('tweet/<int:pk>/delete/', views.tdelete, name='tdelete'),
    path('tweet/<int:pk>/favorite/', views.FavoriteView.as_view(), name='favorite'),
    path('tweet/<int:pk>/favorite/delete', views.FavoriteDeleteView.as_view(), name='fdelete'),
]

pjt00/tclone/models.py
from django.db import models
from django.contrib.auth import get_user_model

class FF(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='ff_user'
    )
    followed = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
        related_name='ff_followed'
    )
    class Meta:
        unique_together = ['user', 'followed']

    def __str__(self):
        return str(self.user)

pjt00/tweet/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Tweet(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    tweet = models.TextField(max_length=140)
    def __str__(self):
        return self.tweet

class Favorite(models.Model):
    user = models.ForeignKey(
        get_user_model(),
        on_delete=models.CASCADE,
    )
    tweet = models.ForeignKey(
        Tweet,
        on_delete=models.CASCADE,
    )
    def __str__(self):
        return self.tweet

pjt00/tclone/forms.py
from django import forms

pjt00/tweet/forms.py
from django import forms
from .models import Tweet


class TweetForm(forms.ModelForm):
    class Meta:
        model = Tweet
        fields = ('tweet',)

pjt00/tclone/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView, FormView, TemplateView
from .models import FF


class TopView(TemplateView):
    template_name = 'tclone/top.html'

class EntryUserView(FormView):
    form_class = UserCreationForm
    template_name = 'tclone/entry.html'
    success_url = reverse_lazy('tclone:entryok')
    def form_valid(self, form):
        status = self.request.POST['proceed']
        if status == 'go':
            return render(
                self.request,
                'tclone/entryconfirm.html',
                {'form': form}
                )
        elif status == 'judge':
            form.save()
            return super().form_valid(form)
        else:
            return(reverse_lazy('tclone:top'))

class EntryOKView(TemplateView):
    template_name = 'tclone/entryok.html'

class FollowView(LoginRequiredMixin, CreateView):
    model = FF
    fields = []
    template_name = 'tclone/follow.html'
    success_url = reverse_lazy('tweet:home')
    def form_valid(self, form):
        model = form.save(commit=False)
        model.user = get_user_model().objects.get(pk=self.request.user.id)
        model.followed = get_object_or_404(
            get_user_model(),
            pk=self.kwargs['pk']
            )
        if model.user == model.followed:
            form.add_error(None,'なぜかあなた自身をフォローしようとしています')
            return super().form_invalid(form)
        elif FF.objects.filter(user=model.user, followed=model.followed).exists():
            form.add_error(None,'もうフォロー済みです')
            return super().form_invalid(form)
        else:
            model.save()
        return super().form_valid(form)

@require_POST
@login_required
def follow_del(request, pk):
    user = get_user_model().objects.get(pk=request.user.pk)
    followed = get_object_or_404(get_user_model(), pk=pk)
    ff = FF.objects.filter(
        user = user,
        followed = followed
    )
    ff.delete()
    return redirect('tweet:home')

pjt00/tweet/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse_lazy
from django.views.decorators.http import require_POST
from django.views.generic import CreateView,TemplateView, View
from rules.contrib.views import permission_required, objectgetter
from .forms import TweetForm
from .models import Tweet, Favorite
from tclone.models import FF


class HomeView(LoginRequiredMixin, TemplateView):
    template_name = 'tweet/home.html'
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tweets'] = Tweet.objects.all()
        return context

@login_required
def tweet(request):
    if request.method == 'POST':
        form = TweetForm(request.POST)
        if form.is_valid():
            tweet = form.save(commit=False)
            tweet.user = request.user
            tweet.save()
            return redirect('tweet:home')
    else:
        form = TweetForm()
    return render(request, 'tweet/tweet.html', {'form': form})

@login_required
def tdetail(request, pk):
    tweet = get_object_or_404(Tweet, pk=pk)
    favorite = Favorite.objects.filter(user=request.user, tweet=tweet)
    return render(request, 'tweet/tdetail.html', {
        'tweet': tweet,
        'favorite':favorite
        })

@permission_required('tweet.can_tedit',fn=objectgetter(Tweet, 'pk'))
def tedit(request, pk):
    tweet = get_object_or_404(Tweet, pk=pk)
    if request.method == 'POST':
        form = TweetForm(request.POST, instance=tweet)
        if form.is_valid():
            tweet.save()
            return redirect('tweet:home')
    else:
        form = TweetForm(instance=tweet)
    return render(request, 'tweet/tweet.html', {'form': form})

@require_POST
@permission_required('tweet.can_tedit',fn=objectgetter(Tweet, 'pk'))
def tdelete(request, pk):
    tweet = get_object_or_404(Tweet, pk=pk)
    tweet.delete()
    return redirect('tweet:home')

@login_required
def profile(request, pk):
    user = get_object_or_404(get_user_model(), pk=pk)
    tweets = Tweet.objects.filter(user=user)
    ff = FF.objects.filter(user=request.user, followed=user)
    return render(request, 'tweet/profile.html',
        {
        'user': user,
        'tweets': tweets,
        'ff': ff
        }
    )

class FavoriteView(LoginRequiredMixin, CreateView):
    model = Favorite
    fields = []
    template_name = 'tweet/favorite.html'
    success_url = reverse_lazy('tweet:home')
    def form_valid(self, form):
        model = form.save(commit=False)
        model.user = get_user_model().objects.get(pk=self.request.user.id)
        model.tweet = get_object_or_404(
            Tweet,
            pk = self.kwargs['pk']
            )
        if Favorite.objects.filter(user=model.user, tweet=model.tweet):
            form.add_error(None, 'You have already favorite this tweet, sorry.')
            return super().form_invalid(form)
        else:
            model.save()
        return super().form_valid(form)

class FavoriteDeleteView(LoginRequiredMixin, View):
    def post(self, request, pk):
        user = get_user_model().objects.get(pk=request.user.pk)
        tweet = get_object_or_404(Tweet, pk=pk)
        favorite = Favorite.objects.filter(
            user = user,
            tweet = tweet
            )
        favorite.delete()
        return redirect('tweet:home')

pjt00/tclone/templates/tclone/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
        Twitter Clone Web Application
      {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style0.css' %}">
  </head>
  <body>
    <header>
      <h1>Twitter Clone Web Application</h1>
    </header>
    <section>
      <div class="subhead">
        <h1>
          {% block subhead %}
            Twitter Clone Web Application へようこそ！
          {% endblock %}
        </h1>
        <p>
          {% block log %}
          {% if user.is_authenticated %}
            <a href="{% url 'tweet:home' %}">{{ user }} のホーム</a>
            /
            <a href="{% url 'tclone:logout' %}"><em>ログアウト</em></a>
          {% else %}
            <a href="{% url 'tclone:login' %}"><em>ログイン</em></a>
          {% endif %}
          {% endblock %}
        </p>
      </div>
      <div class='body'>
        {% block content %}
        {% endblock %}
      </div>
    </section>
    <footer>

    </footer>
  </body>
</html>

pjt00/tclone/templates/tclone/entry.html
{% extends "tclone/base.html" %}
{% block title %}Entry -{{ block.super }}{% endblock %}
{% block log %}{% endblock %}
{% block content %}
  <h1>ユーザー登録</h1>
  <form class="entryform" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="proceed" value="go">確認画面へ</button>
  </form>
{% endblock %}

pjt00/tclone/templates/tclone/entryconf.html
{% extends "tclone/base.html" %}
{% block title %}Entry -{{ block.super }}{% endblock %}
{% block content %}
  以下の内容で登録します。
  <table  class="ui celled table table table-hover" >
    <tr><td>お名前</td><td>{{form.cleaned_data.username}}</td></tr>
    <tr><td>パスワード</td><td>セキュリティのため表示されません</td></tr>
  </table>
  <form class="entryform" method="POST">
    {% csrf_token %}
    {% for field in form %}
    {{field.as_hidden}}
    {% endfor %}
    <a href="../entry">修正</a>
    <button name='proceed' value='judge'>登録</button>
  </form>
{% endblock %}

pjt00/tclone/templates/tclone/entryconfirm.html
{% extends "tclone/base.html" %}
{% block title %}Entry -{{ block.super }}{% endblock %}
{% block log %}{% endblock %}
{% block content %}
  以下の内容で登録します。
  <table  class="ui celled table table table-hover" >
    <tr><td>お名前</td><td>{{form.cleaned_data.username}}</td></tr>
    <tr><td>パスワード</td><td>セキュリティのため表示されません</td></tr>
  </table>
  <form class="entryform" method="POST">
    {% csrf_token %}
    {% for field in form %}
    {{field.as_hidden}}
    {% endfor %}
    <a href="{% url 'tclone:entry' %}">修正</a>
    <button name='proceed' value='judge'>登録</button>
  </form>
{% endblock %}

pjt00/tclone/templates/tclone/entryok.html
{% extends "tclone/base.html" %}
{% block title %}OK -{{ block.super }}{% endblock %}
{% block log %}{% endblock %}
{% block content %}
ユーザー登録に成功しました。<br>
<a href="{% url 'tclone:top' %}">トップページ</a>へ戻り、ログインしてください。
{% endblock %}

pjt00/tclone/templates/tclone/follow.html
{% extends "tclone/base.html" %}
{% block title %}Follow -{{ block.super }}{% endblock %}
{% block content %}
フォローします
<form name='follow' method="POST">
  {% csrf_token %}
  {{ form.as_p }}
  <input type="submit" value='フォロー'>
</form>
{% endblock %}

pjt00/tclone/templates/tclone/top.html
{% extends "tclone/base.html" %}
{% block content %}
  <p>Twitter Clone Web Applicationのご利用には会員登録が必要です。</p>
  <div class="entryuser">
    <p>
      <a href="{% url 'tclone:entry' %}">会員登録</a>
    </p>
  </div>
{% endblock %}

pjt00/tclone/templates/tclone/tweet.html
{% extends "tclone/base.html" %}
{% block title %}Tweet -{{ block.super }}{% endblock %}
{% block welcome %}
  {{ user }} でログインしています
{% endblock %}
{% block content %}
  <form class="tweetform" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="tweet">ツイート</button>
  </form>
{% endblock %}

pjt00/tweet/templates/tweet/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ja" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>
      {% block title %}
        Twitter Clone Web Application
      {% endblock %}
    </title>
    <link rel="stylesheet" type="text/css" href="{% static 'css/style0.css' %}">
  </head>
  <body>
    <header>
      <h1>Twitter Clone Web Application</h1>
    </header>
    <section>
      <div class="subhead">
        <h1>
          {% block subhead %}
            {{ request.user }} でログインしています
          {% endblock %}
        </h1>
        <p>
          {% block log %}
          {% if user.is_authenticated %}
            <a href="{% url 'tweet:home' %}">ホーム</a>
            /
            <a href="{% url 'tweet:tweet' %}">ツイートする</a>
            /
            <a href="{% url 'tclone:logout' %}"><em>ログアウト</em></a>
          {% else %}
            <a href="{% url 'tclone:login' %}"><em>ログイン</em></a>
          {% endif %}
          {% endblock %}
        </p>
      </div>
      <div class='body'>
        {% block content %}
        {% endblock %}
      </div>
    </section>
    <footer>

    </footer>
  </body>
</html>


pjt00/tweet/templates/tweet/favorite.html
{% extends "tclone/base.html" %}
{% block title %}Follow -{{ block.super }}{% endblock %}
{% block content %}
いいねします
<form name='favorite' method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="いいね">
</form>
{% endblock %}

pjt00/tweet/templates/tweet/home.html
{% extends "tweet/base.html" %}
{% block title %}Home -{{ block.super }}{% endblock %}
{% block content %}
  <h1>タイムライン</h1>
  {% for tweet in tweets reversed %}
    <em><a href="{% url 'tweet:profile' pk=tweet.user.pk %}">{{ tweet.user }}</a></em> / <a href="{% url 'tweet:tdetail' pk=tweet.pk %}">詳細</a>
    <p>{{ tweet.tweet }}</p>
  {% endfor %}
{% endblock %}

pjt00/tweet/templates/tweet/profile.html
{% extends "tweet/base.html" %}
{% block title %}{{ user }} -{{ block.super }}{% endblock %}
{% block content %}
<h1>{{ user }} さんのツイート</h1>
{% if user.id is not request.user.id %}
  {% if not ff %}
  <p>
    <form name='follow' action="{% url 'tclone:follow' pk=user.pk %}" method="POST">
      フォローしていません！
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" onclick='return confirm("フォローしますか？");'>フォロー</button>
    </form>
  </p>
  {% else %}
  <p>
    <form class="delete_confirm" action="{% url 'tclone:follow_del' pk=user.pk %}" method="post">
      フォローしています！
      {% csrf_token %}
      <button type="submit" onclick='return confirm("解除しますか？");'>フォロー解除</button>
    </form>
  </p>
  {% endif %}
{% else %}
    <p>
      あなたのツイートが表示されています！
    </p>
{% endif %}
{% for tweet in tweets reversed %}
  <em><a href="{% url 'tweet:profile' pk=tweet.user.pk %}">{{ tweet.user }}</a></em> / <a href="{% url 'tweet:tdetail' pk=tweet.pk %}">詳細</a>
  <p>{{ tweet }}</p>
{% endfor %}
{% endblock %}

pjt00/tweet/templates/tweet/tdetail.html
{% extends "tweet/base.html" %}
{% block title %}Tweet by {{ tweet.user }}-{{ block.super }}{% endblock %}
{% block content %}
  <p><a href="{% url 'tweet:profile' pk=tweet.user.pk %}">{{ tweet.user }}</a></p>
  <p>{{ tweet.tweet }}</p>
  {% if request.user.id == tweet.user.id %}
    <form class="delete_confirm" action="{% url 'tweet:tdelete' tweet.pk %}" method="post">
      {% csrf_token %}
      <a href="{% url 'tweet:tedit' pk=tweet.pk %}">編集</a> /
      <button type="submit" onclick='return confirm("削除しますか？");'>削除</button>
    </form>
  {% endif %}
{% if not favorite %}
    お気に入り登録
<form name='follow' action="{% url 'tweet:favorite' pk=tweet.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">☆</button>
</form>
{% else %}
      お気に入り解除
<form name="follow_del" action="{% url 'tweet:fdelete' pk=tweet.pk %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" onclick="return confirm('お気に入りを解除しますか？');">★</button>
</form>
{% endif %}
{% endblock %}

pjt00/tweet/templates/tweet/tweet.html
{% extends "tweet/base.html" %}
{% block title %}Tweet -{{ block.super }}{% endblock %}
{% block content %}
  <form class="tweetform" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="tweet">ツイート</button>
  </form>
{% endblock %}